---
title: "ChatData Overview"
author: "Mike Wise"
date: "26 Feb 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialization
```{r}
library(tidyverse,quietly=T,warn.conflicts=F)
library(lubridate,quietly=T,warn.conflicts=F)
library(scales,quietly=T,warn.conflicts=F)

set.seed(1234)
version <-0.1
versionstring <- sprintf("Version %.1f",version)

starttime <- Sys.time()
startfmttime <- sprintf(format(starttime, "%d %b %Y - %H:%M:%S"))

print(sprintf("%s created on %s",versionstring,startfmttime))

```

```{r}
addvlines <- function(vlines){
  abl <- function(l) {abline(v=as.POSIXct((l[[1]])),col=l[[2]])}
  sar <- strsplit(vlines,"/")
  jnk <- sapply(sar,abl)
}
sumandcoef <- function(fit){
  if (printsumm){ summary(fit) }
  if (printcoef){ coeftest(fit, vcov = vcovHC(fit, "HC1"))}
}
dailyplt <- function(x,y,mtit="",xlab="date",ylab=NULL,vlines=smcdates){
  ymx <- max(y) + 1000
  plot( x,y, main = mtit,xlab = xlab,ylab=ylab,ylim=c(0,ymx),pch=19,type="l" )
  if (!is.null(vlines)){
    addvlines(vlines)
  }
}
ggdailyplt <- function(x,y,mtit="",xlab="date",ylab=NULL,vlines=NULL,backg=NULL,series=NULL){
  if (is.null(ylab)){
    ylab <- substitute(y)
  }
  ymax <- max(y)*1.05
  ddf <- data.frame(x=x,y=y)
  if(!is.null(series)){
    gp <- ggplot(ddf,aes(x,y)) + geom_line(aes_string(color=series)) 
  } else {
    gp <- ggplot(ddf) + geom_line(aes(x,y)) 
  }
  gp <- gp+ xlab(xlab) + ylab(ylab) + ggtitle(mtit) +
            scale_y_continuous(limits=c(0,ymax)) +
            scale_x_datetime("Date",breaks = date_breaks("1 months"))
  if (!is.null(vlines)){
    # split the lines and convert to data.frame
    sar <- strsplit(vlines,"/")
    # the following reforms the date strings into a data.frame for geom_vline
    ldf <- data.frame(t(matrix(unlist(sar),length(sar[[1]]),length(sar))))
    names(ldf) <- c("dt","clr","lab")
    ldf$dt <- as.POSIXct(ldf$dt,tz=tztz)
    ldf$ndt <- as.numeric(ldf$dt)
    ldf$lab <- paste0("\n",ldf$lab)
    gp <- gp + geom_vline(xintercept=ldf$ndt,color=ldf$clr) +
               annotate(geom="text",x=ldf$dt,y=0,label=ldf$lab,color=ldf$clr,hjust=0,angle=90)
  }
  if (!is.null(backg)){
     gp <- gp + theme(panel.background = element_rect(fill = backg))
  }
  return(gp)
}
```

```{r}
tztz <- "US/Pacific"
fname <- "data/chat-vol-duration-features.csv"

smcdates <- c("2016-08-17/red/0-30%","2016-09-1/red/30-50%","2016-09-07/red/50-100%","2016-11-17/blue/content change")
xabdates <- c("2016-10-11/red/0-10%","2016-10-18/red/10-30%","2016-11-01/red/30-50%","2016-11-17/blue/content change","2016-12-15/red/50-90%")
smcback <- "lightsteelblue1"
xabback <- "darkseagreen2"

fname <- "data/chat-vol-duration-features.csv"
fname <- "../data/chat_volume_duration_features-Aug2016-current.csv"

cvdf <- read.csv(fname)
cvdf$BlockBeginTime1 <- gsub("3/13/2016 2:","3/13/2016 3:",cvdf$BlockBeginTime)
cvdf$DateHour1 <- gsub("3/13/2016 2:","3/13/2016 3:",cvdf$DateHour)
cvdf$bbt <- as.POSIXct(cvdf$BlockBeginTime1,format="%m/%d/%Y %I:%M:%S %p",tz=tztz)
cvdf$dtd <- as.POSIXct(cvdf$Date,format="%m/%d/%Y %I:%M:%S %p",tz=tztz)
cvdf$dt <- as.POSIXct(cvdf$DateHour1,format="%m/%d/%Y %I:%M:%S %p",tz=tztz)
cvdf$dnum <- round(as.numeric(difftime(cvdf$dtd,as.POSIXct("2015-01-01",tz=tztz),"days")),0)

# get rid of everything before July 2016
cutdate <- "2016-07-01"
print(sprintf("Rows before filtering from %s were %d",cutdate,nrow(cvdf)))
cvdf <- cvdf[cvdf$dt>as.POSIXct(cutdate,tz=tztz),]
print(sprintf("Rows after  filtering from %s were %d",cutdate,nrow(cvdf)))
```

# Note that IsSMX and IsSMC are almost mutually exclusive, so we split them

```{r}
xtabs(~ IsSMC + IsSXC,cvdf)
smcdf <- cvdf[cvdf$IsSMC=="True",]
sxcdf <- cvdf[cvdf$IsSXC=="True",]
print(sprintf("smcdf rows:%d",nrow(smcdf)))
print(sprintf("sxcdf rows:%d",nrow(sxcdf)))
```


# SMC daily plots
```{r fig.width=14, fig.height=6, echo=F}
df <- smcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cib = sum(ChatsInBlock))
ggdailyplt(df$dt,df$cib,"SMC - Chats In Block",ylab="Sum",vlines=smcdates,backg=smcback)
```


```{r fig.width=14, fig.height=6, echo=F}
df <- smcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cmins = sum(ChatsInBlock*MeanChatDuration) )
ggdailyplt(df$dt,df$cmins,"SMC - Chat Minutes",ylab="Sum",vlines=smcdates,backg=smcback)
```
```{r fig.width=14, fig.height=6, echo=F}
df <- smcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cmins = sum(CumulativeChatDuration) )
ggdailyplt(df$dt,df$cmins,"SMC - Cummulative Chat Duration",ylab="Sum",vlines=smcdates,backg=smcback)
```



```{r fig.width=14, fig.height=6, echo=F}
df <- smcdf %>% group_by(dnum) %>% summarize(dt=min(dt),entrycount = n())
ggdailyplt(df$dt,df$entrycount,"SMC - Entry Count",ylab="Count",vlines=smcdates,backg=smcback)
```

# SXC daily plot

```{r fig.width=14, fig.height=6, echo=F}
df <- sxcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cib = sum(ChatsInBlock) )
ggdailyplt(df$dt,df$cib,"SXC - Chats In Block",ylab="Sum",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=F}
df <- sxcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cmins = sum(ChatsInBlock*MeanChatDuration) )
ggdailyplt(df$dt,df$cmins,"SXC - Chat Minutes",ylab="Sum",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=F}
df <- sxcdf %>% group_by(dnum) %>% summarize(dt=min(dt),entrycount=n() )
ggdailyplt(df$dt,df$entrycount,"SXC - Entry Count",ylab="Count",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=F}
#df <- sxcdf %>% group_by(dnum,XboxVA) %>% summarize(dt=min(dt),count = n() )
#df$dt <- as.POSIXct(as.Date(df$dt,tz=tztz),tz=tztz)
#ggdailyplt(df$dt,df$count,"SXC - XboxVA",ylab="Sum",vlines=xabdates,backg=xabback,area=T)
```


# Done
```{r echo=F}
elap <- as.numeric((Sys.time()-starttime)[1],units="secs")
print(sprintf("%s created on %s took %.1f secs",versionstring,startfmttime,elap))
```