---
title: "CA Virtual Agent Percentage Regression"
author: "Mike Wise"
date: "1 Mar 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialization
```{r}
library(tidyverse,quietly=T,warn.conflicts=F)
library(lubridate,quietly=T,warn.conflicts=F)
library(scales,quietly=T,warn.conflicts=F)

set.seed(1234)
version <-0.5
versionstring <- sprintf("Version %.1f",version)

starttime <- Sys.time()
startfmttime <- sprintf(format(starttime, "%d %b %Y - %H:%M:%S"))

print(sprintf("%s created on %s",versionstring,startfmttime))

```

```{r}
dailyplot <- function(x,y,mtit="",xlab="date",ylab=NULL,vlines=NULL,backg=NULL){
  ymax <- max(y)*1.05
  ddf <- data.frame(x=x,y=y)
  gp <- ggplot(ddf) + geom_line(aes(x,y))  +
            xlab(xlab) + ylab(ylab) + ggtitle(mtit) +
            scale_y_continuous(limits=c(0,ymax)) +
            scale_x_datetime("Date",breaks = date_breaks("1 months"))
  if (!is.null(vlines)){
    # split the lines and convert to data.frame
    sar <- strsplit(vlines,"/")
    # the following reforms the date strings into a data.frame for geom_vline
    ldf <- data.frame(t(matrix(unlist(sar),length(sar[[1]]),length(sar))))
    names(ldf) <- c("dt","clr","lab")
    ldf$dt <- as.POSIXct(ldf$dt,tz=tztz)
    ldf$ndt <- as.numeric(ldf$dt)
    ldf$lab <- paste0("\n",ldf$lab)
    gp <- gp + geom_vline(xintercept=ldf$ndt,color=ldf$clr) +
               annotate(geom="text",x=ldf$dt,y=0,label=ldf$lab,color=ldf$clr,hjust=0,angle=90)
  }
  if (!is.null(backg)){
     gp <- gp + theme(panel.background = element_rect(fill = backg))
  }
  return(gp)
}
dailyplot2 <- function(x,y,z,mtit="",xlab="date",ylab=NULL,vlines=NULL,backg=NULL){
  zlab <- substitute(z)
  ymax <- max(y)*1.05
  ddf <- data.frame(x=x,y=y,z=z)
  names(ddf)[3] <- as.character(zlab)
  print(head(ddf))
  gp <- ggplot(ddf,aes(x,y)) + geom_line(aes_string(color=zlab)) +
            xlab(xlab) + ylab(ylab) + ggtitle(mtit) +
            scale_y_continuous(limits=c(0,ymax)) +
            scale_x_datetime("Date",breaks = date_breaks("1 months"))
  if (!is.null(vlines)){
    # split the lines and convert to data.frame
    sar <- strsplit(vlines,"/")
    # the following reforms the date strings into a data.frame for geom_vline
    ldf <- data.frame(t(matrix(unlist(sar),length(sar[[1]]),length(sar))))
    names(ldf) <- c("dt","clr","lab")
    ldf$dt <- as.POSIXct(ldf$dt,tz=tztz)
    ldf$ndt <- as.numeric(ldf$dt)
    ldf$lab <- paste0("\n",ldf$lab)
    gp <- gp + geom_vline(xintercept=ldf$ndt,color=ldf$clr) +
               annotate(geom="text",x=ldf$dt,y=0,label=ldf$lab,color=ldf$clr,hjust=0,angle=90)
  }
  if (!is.null(backg)){
     gp <- gp + theme(panel.background = element_rect(fill = backg))
  }
  return(gp)
}
```

```{r}
tztz <- "US/Pacific"

smcdates <- c("2016-08-17/red/0-30%","2016-09-1/red/30-50%","2016-09-07/red/50-100%")
xabdates <- c("2016-10-11/red/0-10%","2016-10-18/red/10-30%","2016-11-01/red/30-50%","2016-12-15/red/50-90%",
              "2016-11-17/blue/content change")
smcback <- "lightsteelblue1"
xabback <- "darkseagreen2"

addStepDate <- function(dates,idx,dtvek,vvek){
  sar1 <- unlist(strsplit(dates[[idx]],"/"))
  dt1 <- as.POSIXct(sar1[[1]],tz=tztz)
  if (idx<length(dates)){
    sar2 <- unlist(strsplit(dates[[idx+1]],"/"))
    dt2 <- as.POSIXct(sar2[[1]],tz=tztz)
  } else {
    dt2 <- max(dtvek)
  }
  #print(dt1)
  #print(dt2)
  val <- as.numeric(gsub("%","",unlist(strsplit(sar1[[3]],"-"))[[2]]))
  tochg <-  dt1<=dtvek & dtvek<= dt2
  vvek[ tochg ] <- val
  #print(sprintf("changed %d values to %d",sum(tochg),val))
  return(vvek)
}
addSmcStepDates <- function(dtvek,vvek=NULL){
  if (is.null(vvek)){
    vvek <- rep(0,length(dtvek))
  }
  for (i in 1:length(smcdates)){
    vvek <- addStepDate(smcdates,i,dtvek,vvek)
  }
  return(vvek)
}
addXabStepDates <- function(dtvek,vvek=NULL){
  xabdates1 <- xabdates[1:(length(xabdates)-1)]
  if (is.null(vvek)){
    vvek <- rep(0,length(dtvek))
  }
  for (i in 1:length(xabdates1)){
    vvek <- addStepDate(xabdates1,i,dtvek,vvek)
  }
  return(vvek)
}
firstday <- as.POSIXct("2015-01-01",tz=tztz)
```

# Read in data
```{r}
fname <- "../data/chat_volume_duration_features-Aug2016-current.csv"

cvdf <- read.csv(fname)
cvdf$BlockBeginTime1 <- gsub("3/13/2016 2:","3/13/2016 3:",cvdf$BlockBeginTime)
cvdf$DateHour1 <- gsub("3/13/2016 2:","3/13/2016 3:",cvdf$DateHour)
cvdf$bbt <- as.POSIXct(cvdf$BlockBeginTime1,format="%m/%d/%Y %I:%M:%S %p",tz=tztz)
cvdf$dtd <- as.POSIXct(cvdf$Date,format="%m/%d/%Y %I:%M:%S %p",tz=tztz)
cvdf$dt <- as.POSIXct(cvdf$DateHour1,format="%m/%d/%Y %I:%M:%S %p",tz=tztz)
cvdf$dnum <- round(as.numeric(difftime(cvdf$dtd,firstday,"days")),0)
cvdf$hnum <- cvdf$dnum*24 + hour(cvdf$dt)

# Just USA
cvdf <- cvdf[cvdf$CountryCode=="USA",]

# get rid of everything before July 2016
cutdate <- "2016-08-01"
print(sprintf("Rows before filtering from %s were %d",cutdate,nrow(cvdf)))
cvdf <- cvdf[cvdf$dt>=as.POSIXct(cutdate,tz=tztz),]
print(sprintf("Rows after  filtering from %s were %d",cutdate,nrow(cvdf)))
```

# Xbox vs. SMC

Note that IsSMX and IsSMC are almost mutually exclusive, so we split them

```{r}
xtabs(~ IsSMC + IsSXC,cvdf)
smcdf <- cvdf[cvdf$IsSMC=="True",]
sxcdf <- cvdf[cvdf$IsSXC=="True",]
#smcdf <- smcdf[smcdf$Subject=="TS - Windows",]
print(sprintf("smcdf rows:%d",nrow(smcdf)))
print(sprintf("sxcdf rows:%d",nrow(sxcdf)))
```


# SMC daily plots
```{r fig.width=14, fig.height=6, echo=T}
df <- smcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cib = sum(ChatsInBlock))
dailyplot(df$dt,df$cib,"SMC - Chats In Block",ylab="Sum",vlines=smcdates,backg=smcback)
```


```{r fig.width=14, fig.height=6, echo=T}
df <- smcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cmins = sum(ChatsInBlock*MeanChatDuration) )
dailyplot(df$dt,df$cmins,"SMC - Chat Minutes",ylab="Sum",vlines=smcdates,backg=smcback)
```


```{r fig.width=14, fig.height=6, echo=T}
df <- smcdf %>% group_by(dnum) %>% summarize(dt=min(dt),entrycount = n())
dailyplot(df$dt,df$entrycount,"SMC - Entry Count",ylab="Count",vlines=smcdates,backg=smcback)
```

# SXC daily plot

```{r fig.width=14, fig.height=6, echo=T}
df <- sxcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cib = sum(ChatsInBlock) )
dailyplot(df$dt,df$cib,"SXC - Chats In Block",ylab="Sum",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=T}
df <- sxcdf %>% group_by(dnum) %>% summarize(dt=min(dt),cmins = sum(ChatsInBlock*MeanChatDuration) )
dailyplot(df$dt,df$cmins,"SXC - Chat Minutes",ylab="Sum",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=T}
df <- sxcdf %>% group_by(dnum) %>% summarize(dt=min(dt),entrycount=n() )
dailyplot(df$dt,df$entrycount,"SXC - Entry Count",ylab="Count",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=T}
df <- smcdf %>% group_by(dnum,XboxVA) %>% summarize(dt=min(dt),count = n() )
df$dt <- as.POSIXct(as.Date(df$dt,tz=tztz),tz=tztz)
XboxVA <- df$XboxVA
dailyplot2(df$dt,df$count,XboxVA,"SMC - XboxVA",ylab="Count",vlines=smcdates,backg=smcback)
```

```{r fig.width=14, fig.height=6, echo=T}
df <- sxcdf %>% group_by(dnum,XboxVA) %>% summarize(dt=min(dt),count = n() )
df$dt <- as.POSIXct(as.Date(df$dt,tz=tztz),tz=tztz)
XboxVA <- df$XboxVA
dailyplot2(df$dt,df$count,XboxVA,"SXC - XboxVA",ylab="Count",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=T}
df <- smcdf %>% group_by(dnum,PartnerVA) %>% summarize(dt=min(dt),count = n() )
df$dt <- as.POSIXct(as.Date(df$dt,tz=tztz),tz=tztz)
PartnerVA <- df$PartnerVA
dailyplot2(df$dt,df$count,PartnerVA,"SMC - PartnerVA",ylab="Count",vlines=smcdates,backg=smcback)
```
```{r fig.width=14, fig.height=6, echo=T}
df <- sxcdf %>% group_by(dnum,PartnerVA) %>% summarize(dt=min(dt),count = n() )
df$dt <- as.POSIXct(as.Date(df$dt,tz=tztz),tz=tztz)
PartnerVA <- df$PartnerVA
dailyplot2(df$dt,df$count,PartnerVA,"SXC - PartnerVA",ylab="Count",vlines=xabdates,backg=xabback)
```
```{r fig.width=14, fig.height=6, echo=T}
df <- smcdf %>% group_by(dnum,virtualAgent) %>% summarize(cavg=mean(MeanChatDuration),cib=sum(ChatsInBlock),dt=min(dt),count = n() )
df$dt <- as.POSIXct(as.Date(df$dt,tz=tztz),tz=tztz) # trunc to 0:00
virtualAgent <- df$virtualAgent
dailyplot2(df$dt,df$count,virtualAgent,"SMC - virtualAgent",ylab="Count",vlines=smcdates,backg=smcback)
```
```{r fig.width=14, fig.height=6, echo=T}
df1 <- df %>% group_by(dnum) %>% summarize(cavg=mean(cavg),cib=sum(cib),dt=min(dt),count=sum(count)) 
df1$falseCount <- df[df$virtualAgent=="False",]$count
df1$fracVirtual <- 100*(1-df1$falseCount/df1$count)
df1$fracVirtualSoll <- addSmcStepDates(df1$dt)
df2 <- df1 %>% gather(series,pct,fracVirtual:fracVirtualSoll,-dt)
series <- df2$series
dailyplot2(df2$dt,df2$pct,series,"SMC - virtualAgent Percentage",ylab="Percent",vlines=smcdates,backg=smcback)

```
# ChatsInBlock ~ dnum + fracVirtual
```{r}
library(lmtest)
library(sandwich)

scut <- as.POSIXct("2016-08-01",tz=tztz)
ecut <- as.POSIXct("2016-10-01",tz=tztz)
dffit <- df1[scut <= df1$dt & df1$dt <= ecut,] 
dffit$dow <- as.factor(wday(dffit$dt))

fit = glm(cib ~ dnum + dow + fracVirtual, data=dffit)
summary(fit)
coeftest(fit, vcov = vcovHC(fit, "HC1"))
```
# Avg Chat Duration ~ dnum + fracVirtual
```{r}
fit = glm(cavg ~ dnum + dow + fracVirtual, data=dffit)
summary(fit)
coeftest(fit, vcov = vcovHC(fit, "HC1"))
```

# ChatsInBlock ~ dnum + fracVirtualSoll
```{r}
fit = glm(cib ~ dnum + dow + fracVirtualSoll, data=dffit)
summary(fit)
coeftest(fit, vcov = vcovHC(fit, "HC1"))
```
# Avg Chat Duration ~ dnum + fracVirtualSoll
```{r}
fit = glm(cavg ~ dnum + dow + fracVirtualSoll, data=dffit)
summary(fit)
coeftest(fit, vcov = vcovHC(fit, "HC1"))
```


# Done
```{r echo=F}
elap <- as.numeric((Sys.time()-starttime)[1],units="secs")
print(sprintf("%s created on %s took %.1f secs",versionstring,startfmttime,elap))
```