---
title: "SMC Data Overview"
author: "Mike Wise"
date: "27 Feb 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialization
```{r}
library(tidyverse,quietly=T,warn.conflicts=F)
library(lubridate,quietly=T,warn.conflicts=F)
library(scales,quietly=T,warn.conflicts=F)

set.seed(1234)
version <-0.1
versionstring <- sprintf("Version %.1f",version)

starttime <- Sys.time()
startfmttime <- sprintf(format(starttime, "%d %b %Y - %H:%M:%S"))

print(sprintf("%s created on %s",versionstring,startfmttime))

```

```{r}
dailyplot <- function(x,y,mtit="",xlab="date",ylab=NULL,vlines=NULL,backg=NULL){
  ymax <- max(y)*1.05
  ddf <- data.frame(x=x,y=y)
  gp <- ggplot(ddf) + geom_line(aes(x,y))  +
            xlab(xlab) + ylab(ylab) + ggtitle(mtit) +
            scale_y_continuous(limits=c(0,ymax)) +
            scale_x_datetime("Date",breaks = date_breaks("1 months"))
  if (!is.null(vlines)){
    # split the lines and convert to data.frame
    sar <- strsplit(vlines,"/")
    # the following reforms the date strings into a data.frame for geom_vline
    ldf <- data.frame(t(matrix(unlist(sar),length(sar[[1]]),length(sar))))
    names(ldf) <- c("dt","clr","lab")
    ldf$dt <- as.POSIXct(ldf$dt,tz=tztz)
    ldf$ndt <- as.numeric(ldf$dt)
    ldf$lab <- paste0("\n",ldf$lab)
    gp <- gp + geom_vline(xintercept=ldf$ndt,color=ldf$clr) +
               annotate(geom="text",x=ldf$dt,y=0,label=ldf$lab,color=ldf$clr,hjust=0,angle=90)
  }
  if (!is.null(backg)){
     gp <- gp + theme(panel.background = element_rect(fill = backg))
  }
  return(gp)
}
dailyplot2 <- function(x,y,z,mtit="",xlab="date",ylab=NULL,vlines=NULL,backg=NULL){
  zlab <- substitute(z)
  ymax <- max(y)*1.05
  ddf <- data.frame(x=x,y=y,z=z)
  names(ddf)[3] <- as.character(zlab)
  gp <- ggplot(ddf,aes(x,y)) + geom_line(aes_string(color=zlab)) +
            xlab(xlab) + ylab(ylab) + ggtitle(mtit) +
            scale_y_continuous(limits=c(0,ymax)) +
            scale_x_datetime("Date",breaks = date_breaks("1 months"))
  if (!is.null(vlines)){
    # split the lines and convert to data.frame
    sar <- strsplit(vlines,"/")
    # the following reforms the date strings into a data.frame for geom_vline
    ldf <- data.frame(t(matrix(unlist(sar),length(sar[[1]]),length(sar))))
    names(ldf) <- c("dt","clr","lab")
    ldf$dt <- as.POSIXct(ldf$dt,tz=tztz)
    ldf$ndt <- as.numeric(ldf$dt)
    ldf$lab <- paste0("\n",ldf$lab)
    gp <- gp + geom_vline(xintercept=ldf$ndt,color=ldf$clr) +
               annotate(geom="text",x=ldf$dt,y=0,label=ldf$lab,color=ldf$clr,hjust=0,angle=90)
  }
  if (!is.null(backg)){
     gp <- gp + theme(panel.background = element_rect(fill = backg))
  }
  return(gp)
}
```

```{r}
tztz <- "US/Pacific"

smcdates <- c("2016-08-17/red/0-30%","2016-09-1/red/30-50%","2016-09-07/red/50-100%","2016-11-17/blue/content change")
xabdates <- c("2016-10-11/red/0-10%","2016-10-18/red/10-30%","2016-11-01/red/30-50%","2016-11-17/blue/content change","2016-12-15/red/50-90%")
smcback <- "lightsteelblue1"
xabback <- "darkseagreen2"

svfname <- "../data/hourly-smc-traffic.csv"

svdf <- read.csv(svfname)
svdf$sdt <- sprintf("%d-%2.2d-%2.2d %2.2d",svdf$EventUtcYear,svdf$EventUtcMonth,svdf$EventUtcDay,svdf$EventUtcHour)
svdf$dt <- as.POSIXct(svdf$sdt,format="%Y-%m-%d %H",tz=tztz)
svdf$dtd <- as.POSIXct(svdf$sdt,format="%Y-%m-%d",tz=tztz)
svdf$dnum <- round(as.numeric(difftime(svdf$dtd,as.POSIXct("2015-01-01",tz=tztz),"days")),0)

# get rid of everything before July 2016
cutdate <- "2016-06-01"
print(sprintf("Rows before filtering from %s were %d",cutdate,nrow(svdf)))
svdf <- svdf[svdf$dt>=as.POSIXct(cutdate,tz=tztz),]
print(sprintf("Rows after  filtering from %s were %d",cutdate,nrow(svdf)))
svdf$spuratio <- svdf$HourlyActiveSessions / svdf$HourlyActiveUsers

svddf <- svdf %>% group_by(dnum) %>% summarize(dt=min(dt),avhas=mean(HourlyActiveSessions),avhau=mean(HourlyActiveUsers),count = n() )
```


# Hourly Active Sessions
```{r fig.width=14, fig.height=6, echo=F}
dailyplot(svdf$dt,svdf$HourlyActiveSessions,"SMC - Hourly Active Sessions",ylab="Count",vlines=smcdates,backg=smcback)
```


# SMC - Hourly Active Users
```{r fig.width=14, fig.height=6, echo=F}
dailyplot(svdf$dt,svdf$HourlyActiveSessions,"SMC -Hourly Active Users",ylab="Count",vlines=smcdates,backg=smcback)
```
# SMC = Sessions per User Ratio
```{r fig.width=14, fig.height=6, echo=F}
ggplot(svdf) + geom_histogram(aes(svdf$spuratio),binwidth=0.0001) + 
               xlab("Ratio of Sessions per User") +
               theme(panel.background = element_rect(fill = smcback)) 

```
# SMC - Daily Average Hourly Active Sessions
```{r fig.width=14, fig.height=6, echo=F}
dailyplot(svddf$dt,svddf$avhas,"SMC - Daily Average Hourly Active Sessions",ylab="Count",vlines=smcdates,backg=smcback)
```
# Daily Average Hourly Active Users
```{r fig.width=14, fig.height=6, echo=F}
dailyplot(svddf$dt,svddf$avhau,"SMC - Daily Average Hourly Active Users",ylab="Count",vlines=smcdates,backg=smcback)
```
# Done
```{r echo=F}
elap <- as.numeric((Sys.time()-starttime)[1],units="secs")
print(sprintf("%s created on %s took %.1f secs",versionstring,startfmttime,elap))
```